version: '3.8'
name: local-capsulas
services:
  postgres:
    build:
      context: .
    environment:
      POSTGRES_DB: capsulas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: